-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.marshals (
  id text NOT NULL,
  staff_number text NOT NULL,
  first_name text NOT NULL,
  surname text NOT NULL,
  position text NOT NULL,
  residential_address text NOT NULL,
  home_tel_no text DEFAULT 'N/A'::text,
  cell_no text NOT NULL,
  id_number text NOT NULL,
  chief_of_area text NOT NULL,
  indvuna text NOT NULL,
  marital_status text NOT NULL DEFAULT 'Single'::text,
  partner_name text,
  number_of_kids integer NOT NULL DEFAULT 0,
  next_of_kin_full_name text NOT NULL,
  next_of_kin_relationship text NOT NULL,
  next_of_kin_contact_number text NOT NULL,
  region text NOT NULL,
  agreement_accepted boolean NOT NULL DEFAULT true,
  registration_date text NOT NULL,
  field_officer_name text,
  notes text,
  photo_storage_path text,
  signature_storage_path text,
  photo_data_url text,
  signature_data_url text,
  created_at bigint NOT NULL,
  updated_at bigint NOT NULL,
  synced_at bigint,
  sync_status text NOT NULL DEFAULT 'synced'::text,
  server_created_at timestamp with time zone DEFAULT now(),
  server_updated_at timestamp with time zone DEFAULT now(),
  whatsapp_no text,
  auth_user_id uuid,
  is_active boolean DEFAULT true,
  last_login_at timestamp with time zone,
  assigned_route_id text,
  terminal_id text,
  version integer NOT NULL DEFAULT 1,
  CONSTRAINT marshals_pkey PRIMARY KEY (id),
  CONSTRAINT marshals_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.sync_logs (
  id text NOT NULL,
  timestamp bigint NOT NULL,
  action text NOT NULL,
  count integer NOT NULL DEFAULT 0,
  status text NOT NULL,
  message text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT sync_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sync_events (
  id text NOT NULL,
  entity_type text NOT NULL,
  entity_id text NOT NULL,
  operation text NOT NULL CHECK (operation = ANY (ARRAY['INSERT'::text, 'UPDATE'::text, 'DELETE'::text])),
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  idempotency_key text NOT NULL UNIQUE,
  client_id text NOT NULL,
  occurred_at timestamp with time zone NOT NULL,
  applied_at timestamp with time zone NOT NULL DEFAULT now(),
  seq bigint NOT NULL DEFAULT nextval('sync_events_seq_seq'::regclass),
  base_version integer,
  CONSTRAINT sync_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.regions (
  code text NOT NULL,
  name text NOT NULL,
  terminal_name text NOT NULL,
  emergency_number text,
  announcement text,
  version integer NOT NULL DEFAULT 1,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT regions_pkey PRIMARY KEY (code)
);
CREATE TABLE public.routes (
  id text NOT NULL,
  region_code text NOT NULL,
  origin text NOT NULL,
  destination text NOT NULL,
  distance_km numeric NOT NULL CHECK (distance_km > 0::numeric),
  base_fare_e numeric NOT NULL CHECK (base_fare_e >= 0::numeric),
  is_popular boolean NOT NULL DEFAULT false,
  start_time text,
  default_bay text,
  version integer NOT NULL DEFAULT 1,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT routes_pkey PRIMARY KEY (id),
  CONSTRAINT routes_region_code_fkey FOREIGN KEY (region_code) REFERENCES public.regions(code)
);
CREATE TABLE public.vehicles (
  registration_number text NOT NULL,
  vic text UNIQUE,
  make text NOT NULL,
  model text NOT NULL,
  seating_capacity integer NOT NULL CHECK (seating_capacity > 0),
  classification text NOT NULL CHECK (classification = ANY (ARRAY['kombi'::text, 'midbus'::text, 'bus'::text])),
  route_assignment_id text,
  loading_bay text,
  owner_name text,
  owner_phone text,
  owner_operator_id text,
  driver_id text,
  status text NOT NULL DEFAULT 'Waiting'::text,
  current_queue_position integer NOT NULL DEFAULT 0,
  permit_number text,
  permit_status text CHECK ((permit_status = ANY (ARRAY['Active'::text, 'Expired'::text, 'Suspended'::text])) OR permit_status IS NULL),
  permit_issue_date date,
  permit_expiry_date date,
  cof_number text,
  cof_issue_date date,
  cof_expiry_date date,
  last_inspection_date date,
  association text,
  insurance_expiry date,
  roadworthiness_expiry date,
  is_mid_month_addition boolean NOT NULL DEFAULT false,
  registration_date date,
  month_registered text,
  mid_month_join_day integer,
  monthly_sequence_base_index integer,
  monthly_first_turn_history ARRAY DEFAULT ARRAY[]::text[],
  version integer NOT NULL DEFAULT 1,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT vehicles_pkey PRIMARY KEY (registration_number),
  CONSTRAINT vehicles_route_assignment_id_fkey FOREIGN KEY (route_assignment_id) REFERENCES public.routes(id)
);
CREATE TABLE public.drivers (
  id text NOT NULL,
  full_name text NOT NULL,
  national_id text UNIQUE,
  phone text NOT NULL,
  residential_address text,
  date_of_birth date,
  gender text,
  license_number text UNIQUE,
  license_class text,
  pdp_number text,
  pdp_issue_date date,
  pdp_expiry_date date,
  pdp_issuing_authority text,
  pdp_status text,
  emergency_contact_name text,
  emergency_contact_phone text,
  emergency_contact_relation text,
  assigned_vehicle_reg text,
  auth_user_id uuid UNIQUE,
  avatar_seed text,
  profile_picture_url text,
  status text NOT NULL DEFAULT 'Active'::text CHECK (status = ANY (ARRAY['Active'::text, 'Suspended'::text, 'On Leave'::text, 'Off-Duty'::text])),
  version integer NOT NULL DEFAULT 1,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT drivers_pkey PRIMARY KEY (id),
  CONSTRAINT drivers_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.staff (
  id text NOT NULL,
  auth_user_id uuid NOT NULL UNIQUE,
  full_name text NOT NULL,
  email text NOT NULL UNIQUE,
  phone text,
  role text NOT NULL CHECK (role = ANY (ARRAY['super-admin'::text, 'admin'::text, 'fleet-manager'::text, 'inspector'::text])),
  region text,
  terminal_id text,
  is_active boolean NOT NULL DEFAULT true,
  last_login_at timestamp with time zone,
  version integer NOT NULL DEFAULT 1,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT staff_pkey PRIMARY KEY (id),
  CONSTRAINT staff_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.trips (
  id text NOT NULL,
  date date NOT NULL,
  departure_time text NOT NULL,
  arrival_time text,
  route_id text NOT NULL,
  vehicle_reg text NOT NULL,
  driver_id text NOT NULL,
  passenger_count integer NOT NULL CHECK (passenger_count > 0),
  trip_duration_minutes integer,
  delay_reason text,
  status text NOT NULL DEFAULT 'InProgress'::text CHECK (status = ANY (ARRAY['InProgress'::text, 'Completed'::text, 'Cancelled'::text])),
  revenue_szl numeric NOT NULL DEFAULT 0,
  version integer NOT NULL DEFAULT 1,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT trips_pkey PRIMARY KEY (id),
  CONSTRAINT trips_route_id_fkey FOREIGN KEY (route_id) REFERENCES public.routes(id)
);
CREATE TABLE public.marshal_transactions (
  id text NOT NULL,
  marshal_id text NOT NULL,
  timestamp timestamp with time zone NOT NULL,
  date date NOT NULL,
  month text NOT NULL,
  vehicle_reg text NOT NULL,
  amount_szl numeric NOT NULL CHECK (amount_szl > 0::numeric),
  trigger_source text NOT NULL CHECK (trigger_source = ANY (ARRAY['Full Cabin Button'::text, 'Depart Button'::text])),
  version integer NOT NULL DEFAULT 1,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT marshal_transactions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.rank_fee_payments (
  id text NOT NULL,
  timestamp timestamp with time zone NOT NULL,
  vehicle_reg text NOT NULL,
  amount_szl numeric NOT NULL CHECK (amount_szl > 0::numeric),
  payment_method text NOT NULL,
  transaction_ref text UNIQUE,
  status text NOT NULL DEFAULT 'Pending'::text CHECK (status = ANY (ARRAY['Success'::text, 'Pending'::text, 'Failed'::text, 'Reversed'::text])),
  allocation_operational numeric NOT NULL DEFAULT 0,
  allocation_nrtc numeric NOT NULL DEFAULT 0,
  allocation_maintenance numeric NOT NULL DEFAULT 0,
  version integer NOT NULL DEFAULT 1,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT rank_fee_payments_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notifications (
  id text NOT NULL,
  timestamp timestamp with time zone NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['SMS'::text, 'WhatsApp'::text, 'Push'::text])),
  recipient_name text,
  recipient_phone text,
  message text NOT NULL,
  status text NOT NULL DEFAULT 'Sent'::text CHECK (status = ANY (ARRAY['Sent'::text, 'Delivered'::text, 'Failed'::text])),
  version integer NOT NULL DEFAULT 1,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id)
);
CREATE TABLE public.incidents (
  id text NOT NULL,
  timestamp timestamp with time zone NOT NULL,
  reporter_name text NOT NULL,
  reporter_phone text NOT NULL,
  reporter_type text CHECK ((reporter_type = ANY (ARRAY['Commuter'::text, 'Driver'::text])) OR reporter_type IS NULL),
  category text NOT NULL,
  description text NOT NULL,
  vehicle_reg text,
  route_id text,
  status text NOT NULL DEFAULT 'Pending'::text CHECK (status = ANY (ARRAY['Pending'::text, 'Investigating'::text, 'Escalated'::text, 'Resolved'::text])),
  escalated_to text,
  image_url text,
  messages jsonb NOT NULL DEFAULT '[]'::jsonb,
  version integer NOT NULL DEFAULT 1,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT incidents_pkey PRIMARY KEY (id),
  CONSTRAINT incidents_route_id_fkey FOREIGN KEY (route_id) REFERENCES public.routes(id)
);
CREATE TABLE public.traffic_tickets (
  id text NOT NULL,
  ticket_number text NOT NULL UNIQUE,
  timestamp timestamp with time zone NOT NULL,
  vehicle_reg text NOT NULL,
  officer_name text NOT NULL,
  officer_badge text NOT NULL,
  offense_type text NOT NULL,
  amount_szl numeric NOT NULL CHECK (amount_szl > 0::numeric),
  location text,
  status text NOT NULL DEFAULT 'Issued'::text CHECK (status = ANY (ARRAY['Issued'::text, 'Paid'::text, 'Synchronized'::text, 'Challenged'::text])),
  notes text,
  version integer NOT NULL DEFAULT 1,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT traffic_tickets_pkey PRIMARY KEY (id)
);
CREATE TABLE public.permit_renewal_requests (
  id text NOT NULL,
  vehicle_reg text NOT NULL,
  fleet_id text,
  current_permit_number text,
  current_expiry_date date,
  operator text,
  driver text,
  reason_for_renewal text NOT NULL,
  comments text,
  supporting_documents ARRAY DEFAULT ARRAY[]::text[],
  status text NOT NULL DEFAULT 'Pending Admin Approval'::text CHECK (status = ANY (ARRAY['Pending Admin Approval'::text, 'Approved'::text, 'Rejected'::text])),
  timestamp timestamp with time zone NOT NULL,
  request_date date NOT NULL,
  new_permit_number text,
  permit_issue_date date,
  permit_expiry_date date,
  cof_number text,
  cof_issue_date date,
  cof_expiry_date date,
  inspection_date date,
  licensing_office text,
  renewal_notes text,
  approved_by text,
  approval_date date,
  operator_license_number text,
  odometer_reading integer,
  year_of_manufacture integer,
  insurance_policy text,
  concession_id text,
  paid_with_master_card boolean NOT NULL DEFAULT false,
  master_payment_ref text,
  renewal_fee_amount_szl numeric,
  version integer NOT NULL DEFAULT 1,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT permit_renewal_requests_pkey PRIMARY KEY (id)
);
CREATE TABLE public.permit_renewal_archives (
  id text NOT NULL,
  vehicle_reg text NOT NULL,
  previous_permit_number text,
  new_permit_number text NOT NULL,
  issue_date date,
  expiry_date date,
  administrator text NOT NULL,
  renewal_date date NOT NULL,
  comments text,
  supporting_documents ARRAY DEFAULT ARRAY[]::text[],
  version integer NOT NULL DEFAULT 1,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT permit_renewal_archives_pkey PRIMARY KEY (id)
);
CREATE TABLE public.permit_audit_logs (
  id text NOT NULL,
  user_id uuid,
  user_role text,
  date date NOT NULL,
  time text NOT NULL,
  device text,
  action text NOT NULL,
  previous_values jsonb,
  new_values jsonb,
  approval_decision text,
  ip_address inet,
  version integer NOT NULL DEFAULT 1,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT permit_audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT permit_audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.vehicle_virtual_cards (
  id text NOT NULL,
  card_number text NOT NULL UNIQUE,
  cvv_hash text NOT NULL,
  expiry_date text NOT NULL,
  vehicle_reg text NOT NULL UNIQUE,
  vic text NOT NULL,
  cardholder_name text,
  driver_id text,
  driver_name text,
  status text NOT NULL DEFAULT 'Active'::text CHECK (status = ANY (ARRAY['Active'::text, 'Frozen'::text, 'Suspended'::text])),
  balance_szl numeric NOT NULL DEFAULT 0 CHECK (balance_szl >= 0::numeric),
  registration_fee_paid boolean NOT NULL DEFAULT false,
  registration_fee_amount numeric NOT NULL DEFAULT 0,
  registration_fee_date date,
  registration_receipt_ref text,
  card_tier text NOT NULL DEFAULT 'Commercial Concession'::text,
  daily_spend_limit_szl numeric NOT NULL DEFAULT 0,
  qr_payload text,
  version integer NOT NULL DEFAULT 1,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT vehicle_virtual_cards_pkey PRIMARY KEY (id),
  CONSTRAINT vehicle_virtual_cards_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.drivers(id)
);
CREATE TABLE public.virtual_card_transactions (
  id text NOT NULL,
  card_id text NOT NULL,
  timestamp timestamp with time zone NOT NULL,
  type text NOT NULL,
  description text NOT NULL,
  amount_szl numeric NOT NULL CHECK (amount_szl > 0::numeric),
  direction text NOT NULL CHECK (direction = ANY (ARRAY['DEBIT'::text, 'CREDIT'::text])),
  terminal_or_marshal text,
  receipt_number text UNIQUE,
  status text NOT NULL DEFAULT 'Completed'::text,
  version integer NOT NULL DEFAULT 1,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT virtual_card_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT virtual_card_transactions_card_id_fkey FOREIGN KEY (card_id) REFERENCES public.vehicle_virtual_cards(id)
);
CREATE TABLE public.fleet_operators (
  id text NOT NULL,
  name text NOT NULL,
  company_name text NOT NULL,
  phone text NOT NULL,
  email text,
  national_id text UNIQUE,
  tax_number text UNIQUE,
  association text,
  avatar_url text,
  bank_account_ref text,
  operator_license_number text,
  auth_user_id uuid UNIQUE,
  version integer NOT NULL DEFAULT 1,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT fleet_operators_pkey PRIMARY KEY (id),
  CONSTRAINT fleet_operators_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.operator_master_cards (
  id text NOT NULL,
  card_number text NOT NULL UNIQUE,
  cvv_hash text NOT NULL,
  expiry_date text NOT NULL,
  operator_id text NOT NULL UNIQUE,
  operator_name text NOT NULL,
  company_name text NOT NULL,
  balance_szl numeric NOT NULL DEFAULT 0 CHECK (balance_szl >= 0::numeric),
  status text NOT NULL DEFAULT 'Active'::text CHECK (status = ANY (ARRAY['Active'::text, 'Frozen'::text])),
  card_tier text NOT NULL DEFAULT 'Enterprise Master Concession'::text,
  daily_transfer_limit_szl numeric NOT NULL DEFAULT 0,
  version integer NOT NULL DEFAULT 1,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT operator_master_cards_pkey PRIMARY KEY (id),
  CONSTRAINT operator_master_cards_operator_id_fkey FOREIGN KEY (operator_id) REFERENCES public.fleet_operators(id)
);
CREATE TABLE public.operator_card_transactions (
  id text NOT NULL,
  card_id text NOT NULL,
  timestamp timestamp with time zone NOT NULL,
  type text NOT NULL,
  description text NOT NULL,
  target_vehicle_reg text,
  target_driver_name text,
  category text,
  amount_szl numeric NOT NULL CHECK (amount_szl > 0::numeric),
  direction text NOT NULL CHECK (direction = ANY (ARRAY['DEBIT'::text, 'CREDIT'::text])),
  receipt_number text UNIQUE,
  payment_method text,
  status text NOT NULL DEFAULT 'Completed'::text,
  version integer NOT NULL DEFAULT 1,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT operator_card_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT operator_card_transactions_card_id_fkey FOREIGN KEY (card_id) REFERENCES public.operator_master_cards(id)
);
CREATE TABLE public.adverts (
  id text NOT NULL,
  title text NOT NULL,
  sponsor_name text NOT NULL,
  image_url text NOT NULL,
  target_regions ARRAY NOT NULL DEFAULT ARRAY['All'::text],
  is_active boolean NOT NULL DEFAULT true,
  file_size_bytes bigint,
  description text,
  promo_code text,
  contact_phone text,
  website_url text,
  category text,
  budget_szl numeric,
  impressions integer NOT NULL DEFAULT 0,
  clicks integer NOT NULL DEFAULT 0,
  start_date date,
  end_date date,
  version integer NOT NULL DEFAULT 1,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT adverts_pkey PRIMARY KEY (id)
);
